# parameters for all capella_ros_dock's nodes

hazards_vector_publisher:
  ros__parameters:
    publisher_topic: "hazard_detection"
    subscription_topics:
    # - "backup_limit"
    # - "bump"
    # - "cliff"
    # - "stalled"
    # - "wheel_drop"
    - "object_proximity"   
    publish_rate: 5

test_dock:
  ros__parameters:
    test_count: 1
    x_min: -150
    x_max: -110
    y_min: -20
    y_max: 20

motion_control:
  ros__parameters:
    max_dock_action_run_time: 160
    min_rotation: 0.10
    max_rotation: 0.20
    go_to_goal_rotation_min: 0.05
    go_to_goal_rotation_max: 0.05
    go_to_goal_translation_min: 0.05
    go_to_goal_translation_max: 0.06
    min_translation: 0.05
    max_translation: 0.20
    angle_to_goal_angle_converged: 0.05
    go_to_goal_angle_too_far: 0.35
    go_to_goal_apply_rotation_angle: 0.01 # when angle_dist > this value,apply rotation
    goal_angle_converged: 0.15
    dist_goal_converged: 0.3
    distance_low_speed: 0.30
    translate_low_speed: 0.05
    rotation_low_speed: 0.10
    second_goal_distance: 0.05 
    buffer_goal_distance: 0.20 # last_docked_distance_offset + distance_low_speed + second_goal_distance +buffer_goal_distance
    deviate_second_goal_x: 0.1
    camera_horizontal_view: 60.0
    localization_converged_time: 3.0 # wait (n) seconds for coordinates to be converged
    tolerance_angle: 0.02
    tolerance_r: 0.02
    dist_error_y_1: 0.05
    dist_error_x_and_y: 0.3
    motion_control_log_level: 'info'
    cmd_vel_hz: 10
    angle_delta: 0.1
    marker_size: 0.12
    dock_valid_obstacle_x: 1.2
    time_sleep: 5.0
    speed_rotation_acceleration: 0.3
    speed_rotation_init_abs: 0.02
    max_action_runtime: 1800
    contacted_keep_move_time: 0.3
    undock_speed: 0.15
    undock_timeout: 30.0
    undock_obstacle_lr: 0.5 # lr, left_right
    undock_obstacle_front: 1.0
    undock_dis: 0.5 # undock要驶离充电桩的距离
    goal_y_correction: 0.0
    go_to_goal_linear_acc: 0.05
    robot_rotate_radius: 1.25
    base_link_y_thr: 0.08
    base_link_dummy_dis: 0.477    # base_link_dummy到base_link的z轴距离，等于环境变量BASE_LINK_DUMMY_TRANSFORM_Z
    last_goal_angle_to_x_positive_dis: 0.05
    last_goal_angle_to_x_positive_y: 0.01
    collision_check: true
    collision_predict_time: 5.0
    odom_twist_scale: 0.99
    enable_clear_local_costmap: false # 是否定时清除local_costmap,用于处理local_costmap长时间不更新的情况
    timout_clear_local_costmap: 3.0 # 清除local_costmap时的超时时间
    
    # 定义超时参数 用于处理对接的子过程超时的情况
    timeout_lookup_marker: 30.0
    timeout_angle_to_buffer_point: 30.0
    timeout_move_to_buffer_point: 30.0
    timeout_angle_to_x_positive_orientation: 30.0
    timeout_angle_to_goal: 30.0
    timeout_go_to_goal_position: 30.0
    timeout_goal_angle: 30.0

    charger_contact_condition_type: 0  # 0: BLUETOOTH_ONLY, 1: CAMERA_ONLY, 2: BLUETOOTH_AND_CAMERA; 目前只支持 0,BLUETOOTH_ONLY
    last_docked_distance_offset: 0.30
    camera_baselink_dis: 0.0  # 相机在baselink_dummy_optimize坐标系上x轴上的值，有正负之分


camera_point_cloud_process:
  ros__parameters:
    topic_name: '/camera3/depth/points'
    pub_frequency: 30
    obstacle_x_min: -0.2  # obstacle coordinates range; camera depth frame => (x,right) (y,down) (z,front) use camera orientation for reference
    obstacle_x_max: 0.2
    obstacle_y_min: -1.0
    obstacle_y_max: 0.0
    obstacle_z_min: 0.26
    obstacle_z_max: 0.4
    display_img_depth_pc: false # red for obstacle, blue for NaN， green for free space.

manual_dock:
  ros__parameters:
    pose_x_min: -0.75
    pose_x_max: -0.15
    pose_y_min: -0.1
    pose_y_max: 0.1
    yaw_min: -3.14
    yaw_max: 3.14

coord_optimize:
  ros__parameters:
    thre_odom_data_valid_count: 3
    thre_moving_linear: 0.001
    thre_moving_angular: 0.001
    score_decline_rate: 0.999985
    score_weight_similarity: 0.7 # score_weight_radius = (1.0 - score_weight_similarity)

  